/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dxnrb.ui;

import com.dxnrb.logic.GameManager;
import java.awt.Point;
import java.util.ArrayList;

/**
 *
 * @author danie
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game(ArrayList<String> names) {
        initComponents();
        
        GameManager gameManager = new GameManager(names, 1); // Change ID parameter when doing database
        stockPileSlot.setText(Integer.toString(gameManager.getDrawPile().getCardNumber()));
        
        // The Game JFrame should only focus on making calls to the game manager to update moves for a players turn
        // This JFrame class (GUI) needs to be kept separate from the game logic
        // Create methods in the game manager that the GUI event methods call on and react to whatever the game manager returns
        
        // When you come back, change your card slot labels to buttons
        // Try get the players hand to refill and display on the buttons
        // Have the constructor initialise the "Player x's turn" label, or create a method that is called similar to the renderTable() from the CUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        exitButton = new javax.swing.JButton();
        TableTop = new javax.swing.JPanel();
        BuildPile = new javax.swing.JPanel();
        buildPileBurner = new javax.swing.JPanel();
        buildPile1 = new javax.swing.JPanel();
        buildSlot1 = new javax.swing.JLabel();
        buildPile2 = new javax.swing.JPanel();
        buildSlot2 = new javax.swing.JLabel();
        buildPile3 = new javax.swing.JPanel();
        buildSlot3 = new javax.swing.JLabel();
        buildPile4 = new javax.swing.JPanel();
        buildSlot4 = new javax.swing.JLabel();
        DiscardPile = new javax.swing.JPanel();
        discardPileBurner = new javax.swing.JPanel();
        discardPile1 = new javax.swing.JPanel();
        discardSlot1 = new javax.swing.JLabel();
        discardPile2 = new javax.swing.JPanel();
        discardSlot2 = new javax.swing.JLabel();
        discardPile3 = new javax.swing.JPanel();
        discardSlot3 = new javax.swing.JLabel();
        discardPile4 = new javax.swing.JPanel();
        discardSlot4 = new javax.swing.JLabel();
        stockPile = new javax.swing.JPanel();
        stockPileSlot = new javax.swing.JLabel();
        Hand = new javax.swing.JPanel();
        hand1 = new javax.swing.JPanel();
        handSlot1 = new javax.swing.JLabel();
        hand2 = new javax.swing.JPanel();
        handSlot2 = new javax.swing.JLabel();
        hand3 = new javax.swing.JPanel();
        handSlot3 = new javax.swing.JLabel();
        hand4 = new javax.swing.JPanel();
        handSlot4 = new javax.swing.JLabel();
        hand5 = new javax.swing.JPanel();
        handSlot5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(854, 480));

        exitButton.setBackground(new java.awt.Color(255, 51, 51));
        exitButton.setLabel("X");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        TableTop.setLayout(new java.awt.GridBagLayout());

        BuildPile.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout buildPileBurnerLayout = new javax.swing.GroupLayout(buildPileBurner);
        buildPileBurner.setLayout(buildPileBurnerLayout);
        buildPileBurnerLayout.setHorizontalGroup(
            buildPileBurnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        buildPileBurnerLayout.setVerticalGroup(
            buildPileBurnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BuildPile.add(buildPileBurner);

        buildPile1.setPreferredSize(new java.awt.Dimension(100, 100));

        buildSlot1.setText("Build Slot 1");

        javax.swing.GroupLayout buildPile1Layout = new javax.swing.GroupLayout(buildPile1);
        buildPile1.setLayout(buildPile1Layout);
        buildPile1Layout.setHorizontalGroup(
            buildPile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(buildPile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buildPile1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buildSlot1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        buildPile1Layout.setVerticalGroup(
            buildPile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(buildPile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buildPile1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buildSlot1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        BuildPile.add(buildPile1);

        buildPile2.setPreferredSize(new java.awt.Dimension(100, 100));

        buildSlot2.setText("Build Slot 2");

        javax.swing.GroupLayout buildPile2Layout = new javax.swing.GroupLayout(buildPile2);
        buildPile2.setLayout(buildPile2Layout);
        buildPile2Layout.setHorizontalGroup(
            buildPile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(buildPile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buildPile2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buildSlot2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        buildPile2Layout.setVerticalGroup(
            buildPile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(buildPile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buildPile2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buildSlot2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        BuildPile.add(buildPile2);

        buildPile3.setPreferredSize(new java.awt.Dimension(100, 100));

        buildSlot3.setText("Build Slot 3");

        javax.swing.GroupLayout buildPile3Layout = new javax.swing.GroupLayout(buildPile3);
        buildPile3.setLayout(buildPile3Layout);
        buildPile3Layout.setHorizontalGroup(
            buildPile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(buildPile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buildPile3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buildSlot3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        buildPile3Layout.setVerticalGroup(
            buildPile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(buildPile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buildPile3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buildSlot3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        BuildPile.add(buildPile3);

        buildPile4.setPreferredSize(new java.awt.Dimension(100, 100));

        buildSlot4.setText("Build Slot 4");

        javax.swing.GroupLayout buildPile4Layout = new javax.swing.GroupLayout(buildPile4);
        buildPile4.setLayout(buildPile4Layout);
        buildPile4Layout.setHorizontalGroup(
            buildPile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(buildPile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buildPile4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buildSlot4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        buildPile4Layout.setVerticalGroup(
            buildPile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(buildPile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buildPile4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buildSlot4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        BuildPile.add(buildPile4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        TableTop.add(BuildPile, gridBagConstraints);

        DiscardPile.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout discardPileBurnerLayout = new javax.swing.GroupLayout(discardPileBurner);
        discardPileBurner.setLayout(discardPileBurnerLayout);
        discardPileBurnerLayout.setHorizontalGroup(
            discardPileBurnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        discardPileBurnerLayout.setVerticalGroup(
            discardPileBurnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        DiscardPile.add(discardPileBurner);

        discardPile1.setPreferredSize(new java.awt.Dimension(100, 100));

        discardSlot1.setText("Discard Slot 1");

        javax.swing.GroupLayout discardPile1Layout = new javax.swing.GroupLayout(discardPile1);
        discardPile1.setLayout(discardPile1Layout);
        discardPile1Layout.setHorizontalGroup(
            discardPile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(discardPile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(discardPile1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(discardSlot1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        discardPile1Layout.setVerticalGroup(
            discardPile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(discardPile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(discardPile1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(discardSlot1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        DiscardPile.add(discardPile1);

        discardSlot2.setText("Discard Slot 2");

        javax.swing.GroupLayout discardPile2Layout = new javax.swing.GroupLayout(discardPile2);
        discardPile2.setLayout(discardPile2Layout);
        discardPile2Layout.setHorizontalGroup(
            discardPile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(discardPile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(discardPile2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(discardSlot2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        discardPile2Layout.setVerticalGroup(
            discardPile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(discardPile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(discardPile2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(discardSlot2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        DiscardPile.add(discardPile2);

        discardSlot3.setText("Discard Slot 3");

        javax.swing.GroupLayout discardPile3Layout = new javax.swing.GroupLayout(discardPile3);
        discardPile3.setLayout(discardPile3Layout);
        discardPile3Layout.setHorizontalGroup(
            discardPile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(discardPile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(discardPile3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(discardSlot3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        discardPile3Layout.setVerticalGroup(
            discardPile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(discardPile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(discardPile3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(discardSlot3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        DiscardPile.add(discardPile3);

        discardSlot4.setText("Discard Slot 4");

        javax.swing.GroupLayout discardPile4Layout = new javax.swing.GroupLayout(discardPile4);
        discardPile4.setLayout(discardPile4Layout);
        discardPile4Layout.setHorizontalGroup(
            discardPile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(discardPile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(discardPile4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(discardSlot4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        discardPile4Layout.setVerticalGroup(
            discardPile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(discardPile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(discardPile4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(discardSlot4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        DiscardPile.add(discardPile4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        TableTop.add(DiscardPile, gridBagConstraints);

        stockPile.setPreferredSize(new java.awt.Dimension(100, 100));

        stockPileSlot.setText("Stock Pile");

        javax.swing.GroupLayout stockPileLayout = new javax.swing.GroupLayout(stockPile);
        stockPile.setLayout(stockPileLayout);
        stockPileLayout.setHorizontalGroup(
            stockPileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(stockPileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stockPileLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stockPileSlot)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        stockPileLayout.setVerticalGroup(
            stockPileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(stockPileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stockPileLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stockPileSlot)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        TableTop.add(stockPile, gridBagConstraints);

        Hand.setLayout(new java.awt.GridLayout(1, 0));

        hand1.setPreferredSize(new java.awt.Dimension(100, 100));

        handSlot1.setText("Hand Slot 1");

        javax.swing.GroupLayout hand1Layout = new javax.swing.GroupLayout(hand1);
        hand1.setLayout(hand1Layout);
        hand1Layout.setHorizontalGroup(
            hand1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        hand1Layout.setVerticalGroup(
            hand1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Hand.add(hand1);

        handSlot2.setText("Hand Slot 2");

        javax.swing.GroupLayout hand2Layout = new javax.swing.GroupLayout(hand2);
        hand2.setLayout(hand2Layout);
        hand2Layout.setHorizontalGroup(
            hand2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        hand2Layout.setVerticalGroup(
            hand2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Hand.add(hand2);

        handSlot3.setText("Hand Slot 3");

        javax.swing.GroupLayout hand3Layout = new javax.swing.GroupLayout(hand3);
        hand3.setLayout(hand3Layout);
        hand3Layout.setHorizontalGroup(
            hand3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        hand3Layout.setVerticalGroup(
            hand3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Hand.add(hand3);

        handSlot4.setText("Hand Slot 4");

        javax.swing.GroupLayout hand4Layout = new javax.swing.GroupLayout(hand4);
        hand4.setLayout(hand4Layout);
        hand4Layout.setHorizontalGroup(
            hand4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        hand4Layout.setVerticalGroup(
            hand4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Hand.add(hand4);

        handSlot5.setText("Hand Slot 5");

        javax.swing.GroupLayout hand5Layout = new javax.swing.GroupLayout(hand5);
        hand5.setLayout(hand5Layout);
        hand5Layout.setHorizontalGroup(
            hand5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        hand5Layout.setVerticalGroup(
            hand5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(hand5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hand5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(handSlot5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Hand.add(hand5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        TableTop.add(Hand, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Player 1's Turn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TableTop, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TableTop, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        Point location = this.getLocation();
        MainMenu menu = new MainMenu();
        menu.setLocation(location);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuildPile;
    private javax.swing.JPanel DiscardPile;
    private javax.swing.JPanel Hand;
    private javax.swing.JPanel TableTop;
    private javax.swing.JPanel buildPile1;
    private javax.swing.JPanel buildPile2;
    private javax.swing.JPanel buildPile3;
    private javax.swing.JPanel buildPile4;
    private javax.swing.JPanel buildPileBurner;
    private javax.swing.JLabel buildSlot1;
    private javax.swing.JLabel buildSlot2;
    private javax.swing.JLabel buildSlot3;
    private javax.swing.JLabel buildSlot4;
    private javax.swing.JPanel discardPile1;
    private javax.swing.JPanel discardPile2;
    private javax.swing.JPanel discardPile3;
    private javax.swing.JPanel discardPile4;
    private javax.swing.JPanel discardPileBurner;
    private javax.swing.JLabel discardSlot1;
    private javax.swing.JLabel discardSlot2;
    private javax.swing.JLabel discardSlot3;
    private javax.swing.JLabel discardSlot4;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel hand1;
    private javax.swing.JPanel hand2;
    private javax.swing.JPanel hand3;
    private javax.swing.JPanel hand4;
    private javax.swing.JPanel hand5;
    private javax.swing.JLabel handSlot1;
    private javax.swing.JLabel handSlot2;
    private javax.swing.JLabel handSlot3;
    private javax.swing.JLabel handSlot4;
    private javax.swing.JLabel handSlot5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel stockPile;
    private javax.swing.JLabel stockPileSlot;
    // End of variables declaration//GEN-END:variables
}
