/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dxnrb.ui;

import com.dxnrb.logic.GameManager;
import java.awt.CardLayout;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author danie
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    // Game initialisation screen variables
    private JTextField[] playerFields;
    private JLabel[] textFieldLabels;
    
    public MainMenu() {
        initComponents();
        
        // Initialise card layout
        CardLayout menuCard = (CardLayout)(Parent.getLayout());
        
        // Add JPanels to cards
        Parent.add(menu, "menu");
        
        
        Parent.add(instructions, "instructions");
        
        
        Parent.add(gameInit, "gameInit");
        // Create player count spinner
        playerSpinner.setModel(new SpinnerNumberModel(2, 2, 6, 1));
        // Disable typing in spinner (ChatGPT showed me this)
        ((JSpinner.DefaultEditor) playerSpinner.getEditor()).getTextField().setEditable(false);
        // Store object reference for dynamic updating on spinner change event
        playerFields = new JTextField[] {playerTextField1, playerTextField2, playerTextField3, playerTextField4, playerTextField5, playerTextField6};;
        textFieldLabels = new JLabel[] {playerLabel1, playerLabel2, playerLabel3, playerLabel4, playerLabel5, playerLabel6};
        // Initialise visibility on card
        playerSpinnerStateChanged(null);
        
        
        // Show menu panel at start up
        menuCard.show(Parent, "menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parent = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        navigation = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        instructionsButton = new javax.swing.JButton();
        scoreButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        instructions = new javax.swing.JPanel();
        instructionsHeader = new javax.swing.JLabel();
        instructionsText = new javax.swing.JTextArea();
        exitButton_Instructions = new javax.swing.JButton();
        gameInit = new javax.swing.JPanel();
        playerSpinner = new javax.swing.JSpinner();
        spinnerLabel = new javax.swing.JLabel();
        exitButton_gameInit = new javax.swing.JButton();
        dynamicPlayerFields = new javax.swing.JPanel();
        playerTextField1 = new javax.swing.JTextField();
        playerLabel4 = new javax.swing.JLabel();
        playerLabel5 = new javax.swing.JLabel();
        playerLabel6 = new javax.swing.JLabel();
        playerTextField2 = new javax.swing.JTextField();
        namesLabel = new javax.swing.JLabel();
        playerTextField3 = new javax.swing.JTextField();
        playerTextField4 = new javax.swing.JTextField();
        playerTextField5 = new javax.swing.JTextField();
        playerTextField6 = new javax.swing.JTextField();
        playerLabel1 = new javax.swing.JLabel();
        playerLabel2 = new javax.swing.JLabel();
        playerLabel3 = new javax.swing.JLabel();
        startGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(854, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(854, 480));

        Parent.setLayout(new java.awt.CardLayout());

        menu.setPreferredSize(new java.awt.Dimension(854, 480));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dxnrb/img/logo.png"))); // NOI18N

        startButton.setLabel("Start Game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        instructionsButton.setLabel("Instructions");
        instructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsButtonActionPerformed(evt);
            }
        });

        scoreButton.setLabel("Score Board");

        logButton.setLabel("Game Logs");

        javax.swing.GroupLayout navigationLayout = new javax.swing.GroupLayout(navigation);
        navigation.setLayout(navigationLayout);
        navigationLayout.setHorizontalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instructionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        navigationLayout.setVerticalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logButton))
        );

        exitButton.setBackground(new java.awt.Color(255, 51, 51));
        exitButton.setLabel("X");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addContainerGap())
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(logo)
                        .addContainerGap(165, Short.MAX_VALUE))))
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addGap(12, 12, 12)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Parent.add(menu, "card2");

        instructions.setPreferredSize(new java.awt.Dimension(854, 480));

        instructionsHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        instructionsHeader.setText("Instructions");

        instructionsText.setEditable(false);
        instructionsText.setColumns(20);
        instructionsText.setLineWrap(true);
        instructionsText.setRows(5);
        instructionsText.setText("Objective:\nBe the first player to play all the cards in your STOCK pile.\n\nHow To Play:\nUsing your HAND, DISCARD, and STOCK pile, play cards to the BUILD pile.\n\nWhatever card played to a BUILD pile must be the next sequential number.\n\nYour DISCARD piles can be built in any order.\n\nYou can play from your DISCARD pile as many times as you like during your turn.\n\nPlaying your HAND to your DISCARD pile ends your turn.\n\nIf you use up all cards in your HAND during your turn, you replenish your HAND and keep playing.\n\nWildcards (0) can be played as any number 1 through 12.");
        instructionsText.setWrapStyleWord(true);
        instructionsText.setFocusable(false);

        exitButton_Instructions.setBackground(new java.awt.Color(255, 51, 51));
        exitButton_Instructions.setLabel("X");
        exitButton_Instructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton_InstructionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout instructionsLayout = new javax.swing.GroupLayout(instructions);
        instructions.setLayout(instructionsLayout);
        instructionsLayout.setHorizontalGroup(
            instructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton_Instructions)
                .addContainerGap())
            .addGroup(instructionsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(instructionsText, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(instructionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(instructionsHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        instructionsLayout.setVerticalGroup(
            instructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton_Instructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsHeader)
                .addGap(18, 18, 18)
                .addComponent(instructionsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(instructions, "card3");

        gameInit.setPreferredSize(new java.awt.Dimension(854, 480));

        playerSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                playerSpinnerStateChanged(evt);
            }
        });

        spinnerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spinnerLabel.setText("Players");

        exitButton_gameInit.setBackground(new java.awt.Color(255, 51, 51));
        exitButton_gameInit.setLabel("X");
        exitButton_gameInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton_gameInitActionPerformed(evt);
            }
        });

        playerTextField1.setText("Player 1");
        playerTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                playerTextField1FocusGained(evt);
            }
        });

        playerLabel4.setText("4");

        playerLabel5.setText("5");

        playerLabel6.setText("6");

        playerTextField2.setText("Player 2");
        playerTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                playerTextField2FocusGained(evt);
            }
        });

        namesLabel.setText("Player names:");

        playerTextField3.setText("Player 3");
        playerTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                playerTextField3FocusGained(evt);
            }
        });

        playerTextField4.setText("Player 4");
        playerTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                playerTextField4FocusGained(evt);
            }
        });

        playerTextField5.setText("Player 5");
        playerTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                playerTextField5FocusGained(evt);
            }
        });

        playerTextField6.setText("Player 6");
        playerTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                playerTextField6FocusGained(evt);
            }
        });

        playerLabel1.setText("1");

        playerLabel2.setText("2");

        playerLabel3.setText("3");

        startGameButton.setBackground(new java.awt.Color(0, 204, 51));
        startGameButton.setText("Play!");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dynamicPlayerFieldsLayout = new javax.swing.GroupLayout(dynamicPlayerFields);
        dynamicPlayerFields.setLayout(dynamicPlayerFieldsLayout);
        dynamicPlayerFieldsLayout.setHorizontalGroup(
            dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dynamicPlayerFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namesLabel)
                    .addGroup(dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(playerTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(playerTextField2)
                        .addComponent(playerTextField3)
                        .addComponent(playerTextField4)
                        .addComponent(playerTextField5)
                        .addComponent(playerTextField6))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dynamicPlayerFieldsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startGameButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dynamicPlayerFieldsLayout.setVerticalGroup(
            dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dynamicPlayerFieldsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(namesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dynamicPlayerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(startGameButton))
        );

        javax.swing.GroupLayout gameInitLayout = new javax.swing.GroupLayout(gameInit);
        gameInit.setLayout(gameInitLayout);
        gameInitLayout.setHorizontalGroup(
            gameInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameInitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton_gameInit)
                .addContainerGap())
            .addGroup(gameInitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dynamicPlayerFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameInitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354))
        );
        gameInitLayout.setVerticalGroup(
            gameInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameInitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton_gameInit)
                .addGap(29, 29, 29)
                .addGroup(gameInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dynamicPlayerFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(gameInit, "card4");

        getContentPane().add(Parent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to quit the game?", "Quit Game", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        else if (choice == JOptionPane.NO_OPTION)
        {
            return;
        }
        
    }//GEN-LAST:event_exitButtonActionPerformed

    private void instructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsButtonActionPerformed
        // TODO add your handling code here:
        CardLayout menuCard = (CardLayout)(Parent.getLayout());
        menuCard.show(Parent, "instructions");
    }//GEN-LAST:event_instructionsButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        CardLayout menuCard = (CardLayout)(Parent.getLayout());
        menuCard.show(Parent, "gameInit");
    }//GEN-LAST:event_startButtonActionPerformed

    private void exitButton_InstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton_InstructionsActionPerformed
        // TODO add your handling code here:
        CardLayout menuCard = (CardLayout)(Parent.getLayout());
        menuCard.show(Parent, "menu");
    }//GEN-LAST:event_exitButton_InstructionsActionPerformed

    private void exitButton_gameInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton_gameInitActionPerformed
        // TODO add your handling code here:
        CardLayout menuCard = (CardLayout)(Parent.getLayout());
        menuCard.show(Parent, "menu");
    }//GEN-LAST:event_exitButton_gameInitActionPerformed

    private void playerSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_playerSpinnerStateChanged
        // TODO add your handling code here:
        int numPlayers = (int) playerSpinner.getValue();
        
        // Dynamically enable entry fields
        for (int i = 0; i < numPlayers; i++) {
            playerFields[i].setVisible(true);
            textFieldLabels[i].setVisible(true);
        }
        // Dynamically disable entry fields
        for (int i = numPlayers; i < 6; i++) {
            playerFields[i].setVisible(false);
            textFieldLabels[i].setVisible(false);
        }
        
        // Update card
        gameInit.revalidate();
        gameInit.repaint();
    }//GEN-LAST:event_playerSpinnerStateChanged

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        // TODO add your handling code here:
        
        // Read the player names
        ArrayList<String> names = new ArrayList<>();
        for (int i = 0; i < (int) playerSpinner.getValue(); i++) {
            names.add(playerFields[i].getText());
        }
        // For the new instance of the Game JFrame, pass the list of names so it can create a game manager
        Game gameWindow = new Game(names);
        
        // Get this JFrames location and set gameWindows position to match for window continuity
        Point location = this.getLocation();
        gameWindow.setLocation(location);
        gameWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startGameButtonActionPerformed

    private void playerTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playerTextField1FocusGained
        // TODO add your handling code here:
        playerTextField1.selectAll();
    }//GEN-LAST:event_playerTextField1FocusGained

    private void playerTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playerTextField2FocusGained
        // TODO add your handling code here:
        playerTextField2.selectAll();
    }//GEN-LAST:event_playerTextField2FocusGained

    private void playerTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playerTextField3FocusGained
        // TODO add your handling code here:
        playerTextField3.selectAll();
    }//GEN-LAST:event_playerTextField3FocusGained

    private void playerTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playerTextField4FocusGained
        // TODO add your handling code here:
        playerTextField4.selectAll();
    }//GEN-LAST:event_playerTextField4FocusGained

    private void playerTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playerTextField5FocusGained
        // TODO add your handling code here:
        playerTextField5.selectAll();
    }//GEN-LAST:event_playerTextField5FocusGained

    private void playerTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playerTextField6FocusGained
        // TODO add your handling code here:
        playerTextField6.selectAll();
    }//GEN-LAST:event_playerTextField6FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel dynamicPlayerFields;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton_Instructions;
    private javax.swing.JButton exitButton_gameInit;
    private javax.swing.JPanel gameInit;
    private javax.swing.JPanel instructions;
    private javax.swing.JButton instructionsButton;
    private javax.swing.JLabel instructionsHeader;
    private javax.swing.JTextArea instructionsText;
    private javax.swing.JButton logButton;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel namesLabel;
    private javax.swing.JPanel navigation;
    private javax.swing.JLabel playerLabel1;
    private javax.swing.JLabel playerLabel2;
    private javax.swing.JLabel playerLabel3;
    private javax.swing.JLabel playerLabel4;
    private javax.swing.JLabel playerLabel5;
    private javax.swing.JLabel playerLabel6;
    private javax.swing.JSpinner playerSpinner;
    private javax.swing.JTextField playerTextField1;
    private javax.swing.JTextField playerTextField2;
    private javax.swing.JTextField playerTextField3;
    private javax.swing.JTextField playerTextField4;
    private javax.swing.JTextField playerTextField5;
    private javax.swing.JTextField playerTextField6;
    private javax.swing.JButton scoreButton;
    private javax.swing.JLabel spinnerLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JButton startGameButton;
    // End of variables declaration//GEN-END:variables
}
